[package]
name = "blecho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.10.1"
tokio = { version = "1.21.2", features = ["full"] }
uuid = "1.2.1"
